### PR TITLE
responsive v2

### PR DESCRIPTION
**Pull request by shpfive**
updated to new structure and fixed Bug when adding or removing elements from grid 
Please have a look into it :)

_responsive is set via prop_

### CODE REVIEW

**Comment by shpfive** [comment]
When will you look into this?

**Comment by gmsa** [comment]
Hopefully this week

**Comment by gmsa** [comment]
Looks good. Can you update the README with the new properties?

**Comment by shpfive** [comment]
added 
```* **responsive**
    
    * type: `Boolean`
    * required: `false`
    * default: `false`

    Says if the layout should be responsive to window width

* **breakpoints**

    * type: `Object`
    * required: `false`
    * default: { lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }

    Breakpoints defined for responsive layout. Sets widths on wich column number changes

* **cols**

    * type: `Object`
    * required: `false`
    * default: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }

    Defines columns foreach breakpoint width

....

- [x] Responsive

**Comment by gmsa** [comment]
thanks, good job!

**Comment by alc32** [comment]
Can you add an example too?

**Comment by shpfive** [comment]
Just add :responsive="true"

**Comment by gmsa** [comment]
I'll make a release tomorrow and include an example

**Comment by gmsa** [comment]
Example here: https://jbaysolutions.github.io/vue-grid-layout/examples/06-responsive.html

**Comment by alc32** [comment]
Its ordered different in Firefox than in Chrome:

captura de pantalla de 2018-11-28 11-45-32

https://jbaysolutions.github.io/vue-grid-layout/examples/06-responsive.html

**Comment by tripflex** [comment]
@alc32 i'm guessing your response was ignored .. although I can confirm exactly what you're saying and it is still an issue

**Pull request merged**
