### PR TITLE
Added Drag from Outside example page

### PR DESCRIPTION
**Pull request by dhamet70**
An exemple for a DragFromOutside implementation that mimics the react component html page.
https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

( Works on Chrome, Firefox, Edge )

### CODE REVIEW

**Comment by dhamet70** [comment]
Doesn't work on Firefox yet.
(  mouse coordinates bug on drag event )

**Comment by gmsa** [comment]
thanks

**Comment by dhamet70** [comment]
Many thx to you ! Awesome job.

**Comment by guobiinfen** [comment]
hello:
i  want this list add to the grid by draging from outside one by one; but there are many problem; the grid-item will overlap sometimes; Here's my code.  i dont know what happend.
list: [
        { x: 4, y: 28, w: 4, h: 9, i: "subscribe" },
        { x: 0, y: 28, w: 4, h: 9, i: "collection" },
        { x: 0, y: 18, w: 8, h: 10, i: "kb" },
        { x: 0, y: 5, w: 8, h: 13, i: "tenant" },
        { x: 0, y: 0, w: 8, h: 5, i: "access" },
        { x: 0, y: 54, w: 8, h: 5, i: "appApply" },
        { x: 0, y: 0, w: 4, h: 16, i: "kbList" },
        { x: 0, y: 42, w: 12, h: 8, i: "tool" },
        { x: 8, y: 15, w: 4, h: 15, i: "messageTodo" },
        { x: 0, y: 37, w: 4, h: 9, i: "apiSubscribe" },
        { x: 4, y: 37, w: 4, h: 9, i: "apiCollection" },
        { x: 8, y: 0, w: 4, h: 15, i: "message" },
      ],
drag(obj) {
      let parentRect = document.getElementById("content").getBoundingClientRect();
      let mouseInGrid = false;
      if (
        mouseXY.x > parentRect.left &&
        mouseXY.x < parentRect.right &&
        mouseXY.y > parentRect.top &&
        mouseXY.y < parentRect.bottom
      ) {
        mouseInGrid = true;
      }
      console.log(parentRect.top, parentRect);
      if (
        mouseInGrid === true &&
        this.layout.findIndex((item) => item.i === obj.i) === -1
      ) {
        this.layout.push({
          //   x: this.layout.length % (this.colNum || 12),
          //   y: this.layout.length + (this.colNum || 12), // puts it at the bottom
          x: obj.x,
          y: obj.y,
          w: obj.w,
          h: obj.h,
          i: obj.i,
        });
        // this.layout.push(obj)
      }
      let index = this.layout.findIndex((item) => item.i === obj.i);
      //在里面
      if (index !== -1) {
        try {
          this.$refs.gridlayout.$children[this.layout.length].$refs.item.style.display =
            "none";
        } catch {
          console.log("haha");
        }
        let el = this.$refs.gridlayout.$children[index];
        el.dragging = {
          top: mouseXY.y - parentRect.top,
          left: mouseXY.x - parentRect.left,
        };
        let new_pos = el.calcXY(mouseXY.y - parentRect.top, mouseXY.x - parentRect.left);
        if (mouseInGrid === true) {
          this.$refs.gridlayout.dragEvent(
            "dragstart",
            obj.i,
            new_pos.x,
            new_pos.y,
            obj.h,
            obj.w
          );
          DragPos.x = this.layout[index].x;
          DragPos.y = this.layout[index].y;
        }
        if (mouseInGrid === false) {
          this.$refs.gridlayout.dragEvent(
            "dragend",
            obj.i,
            new_pos.x,
            new_pos.y,
            obj.h,
            obj.w
          );
          this.layout = this.layout.filter((item) => item.i !== obj.i);
        }
      }
    },
    dragend(obj) {
      let parentRect = document.getElementById("content").getBoundingClientRect();
      let mouseInGrid = false;
      if (
        mouseXY.x > parentRect.left &&
        mouseXY.x < parentRect.right &&
        mouseXY.y > parentRect.top &&
        mouseXY.y < parentRect.bottom
      ) {
        mouseInGrid = true;
      }
      if (mouseInGrid === true) {
        this.list.filter((item) => item.i !== obj.i);
        this.$refs.gridlayout.dragEvent(
          "dragend",
          obj.i,
          DragPos.x,
          DragPos.y,
          obj.h,
          obj.w
        );
        this.layout = this.layout.filter((item) => obj.i !== item.i);
        // UNCOMMENT below if you want to add a grid-item
        this.layout.push({
          x: DragPos.x,
          y: DragPos.y,
          w: obj.w,
          h: obj.h,
          i: obj.i,
        });
        try {
          this.$refs.gridlayout.$children[this.layout.length].$refs.item.style.display =
            "block";
        } catch {
          console.log("hahha");
        }
      }
    },

**Pull request merged**
