### PR TITLE
initial responsive version

### PR DESCRIPTION
**Pull request by shpfive**
my try for including responsive features.
please look into it and give feedback

### CODE REVIEW

**Comment by gmsa** [comment]
If you run this with ```yarn dev``` it doesn't work:

```
ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-e025cafc"}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/ResponsiveGridLayout.vue
(Emitted value instead of an instance of Error) 
  Error compiling template:
  
  <div ref="item" class="vue-grid-layout" :style="mergedStyle">
      <template v-for="item in actLayout" :key="item.i">
          <slot :item="item"></slot>
      </template>
      <grid-item class="vue-grid-placeholder"
                 v-show="isDragging"
                 :x="placeholder.x"
                 :y="placeholder.y"
                 :w="placeholder.w"
                 :h="placeholder.h"
                 :i="placeholder.i"></grid-item>
  </div>
  
  - <template> cannot be keyed. Place the key on real elements instead.
```

There is no sample for the responsive layout or instructions on how to use it.

**Comment by shpfive** [comment]
i did a quick fix. that was an easy one. should be working now.
you dont have to do anything the sample is the app.vue 

its still not perfect but i think you'll get an idea

**Comment by alc32** [comment]
Is this working?

**Comment by shpfive** [comment]
@alc32 mostly ? i think it can be improve but it works

**Comment by eugenesaenko** [comment]
Why this haven't merged yet?

**Comment by MLongz** [comment]
Will this pr be merged anytime soon in the nearest future?

**Comment by gmsa** [comment]
It wasn't working when I first tried it, I didn't check it after the fix. I hope to have some free time to work on it during the next few weeks.

**Comment by bensladden** [comment]
i have noticed one bug if you add an item on one layout it will not appear on layouts you have already been on.

1. Start on lg layout
2. Move to md layout
3. Add item
4. Move to lg layout and the item will not be there

**Comment by MLongz** [comment]
Any update on this?

**Comment by shpfive** [comment]
had no time to look into the bug @bensladden mentioned. will try as soon as possible

**Comment by MLongz** [comment]
> had no time to look into the bug @bensladden mentioned. will try as soon as possible

I added a comment where the bug is with a fix please have a review. The rest seems to work fine.

**Comment by shpfive** [comment]
@MLongz im sorry but where did you comment ?

**Comment by MLongz** [comment]
@shpfive

ITS seems the comment is pending. This seems to fix the bug where gridItem didnt got copied over to the other breakpoints.

   for (let i = 0, len = breakpointsAbove.length; i < len; i++) {
        const b = breakpointsAbove[i];
        if (layouts[b]) {
            layout = layouts[b];
            if (layouts[b].length !== actLayout.length) {
                let newItem = actLayout[actLayout.length - 1];
                layout.push(newItem)
            }
            break;
        }
    }

But probably have to add a function to Check latest valid item and not last of array. Sinne you can remove items from array.

**Comment by shpfive** [comment]
@MLongz thank you for your help. i fixed it differently but i think it should work
#228 please have a look into it as i updated to new plugin structure

**Pull request closed without merging**
