### PR TITLE
removed event listener in beforeDestroy

### PR DESCRIPTION
**Pull request by Tinoooo**

### CODE REVIEW

**Comment by gmsa** [comment]
Do you need a release with this change?

**Comment by Tinoooo** [comment]
Yes. That would be great :)

**Comment by gmsa** [comment]
Just published 1.0.4 to npmjs

**Comment by Tinoooo** [comment]
Great. Thank you. That fixed a major memory leak for me :+1:

**Comment by gmsa** [comment]
No problem. Just out of curiosity, what tools did you use to find where the leak was?

**Comment by Tinoooo** [comment]
Just Chrome Dev Tools.
I used the three-snapshots-technique (https://www.youtube.com/watch?v=L3ugr9BJqIs).

**Pull request merged**
