### PR TITLE
Added support for min/max y/x on GridItem

### PR DESCRIPTION
**Pull request by jonaslm**
Like min/max h/w, this can clamp the X and Y coordinates of GridItems to the given min and max.

Closed #433 and made a new PR so I could point at another branch that doesn't contain the build files.

### CODE REVIEW

**Comment by sh-winter** [comment]
太棒了，我需要它

**Comment by sh-winter** [comment]
Great. I need it

**Comment by gmsa** [comment]
This doesn't work if you have maxY on an item and you drag another to a position above it, it will move to a position with an Y bigger than maxY

**Comment by jonaslm** [comment]
@gmsa Hmm, you mean if verticalCompact is true, or preventCollision is false, right? It doesn't matter for our use case, but I understand why it might not be desirable (or expected) in the general case.

To elaborate, for our use case (a timeline), only the X axis actually matters (when events are scheduled) - the Y axis exists only to enable us to have several events scheduled at the same time. Therefore we don't want to enable dragging along the Y axis; it implies that it has meaning. But we're also not concerned that the events move along the Y axis, even if this violates their current min/max Y setting (which we just set to their current Y anyway).

I'm not sure how to fix this for the general case - and even if it were fixed, it might not fulfill our demand any longer that way (we'd have to unset min/max-Y on items that are not being dragged, to allow them to be moved/vertically compacted again).

Perhaps the settings could be re-made as a "no-drag-x" or "no-drag-y"? It would limit the item to being dragged only along the allowed axes, but not limit its movement when not being dragged (e.g. when being moved by vertical compaction or collision prevention).

Do you have an opinion on this?

**Comment by gmsa** [comment]
Sorry for the late response. I guess something like "max-drag-x" and "max-drag-y" would make more sense

**Comment by jonaslm** [comment]
I don't have time to rewrite this at the moment, and we're content using my version for our needs right now, so I'll just close the PR.

I might come back at some point and rewrite the solution according to our discussion, we'll see.

**Pull request closed without merging**
