### PR TITLE
Trigger layout-compacted event

### PR DESCRIPTION
**Pull request by pajcho**
This will trigger `layout-compacted` event when the layout is compacted. This is important because there is currently no way we can detect this change when the vertical compact is enabled. 

This can be used as any other layout event: 

```html
<grid-layout 
            :layout="layout"
            :col-num="12"
            :row-height="30"
            :is-draggable="true"
            :is-resizable="true"
            :vertical-compact="true"
            :margin="[10, 10]"
            :use-css-transforms="true"
            @layout-compacted="layoutCompactedEvent">
```

### CODE REVIEW

**Comment by pajcho** [comment]
@gmsa any thoughts about this one? It's very crucial for our use case where we need to persist positions in the database every time they are updated and when vertically compacted no event is being triggered at all. 

I would prefer this feature to be a part of main repository so we don't have to maintain our own version. Thanks.

**Comment by gmsa** [comment]
You already have the layout-read and layout-updated events.

Btw, don't commit package-lock.json and files inside the dist folder

**Comment by pajcho** [comment]
@gmsa Yes, but neither one of those (layout-ready and layout-updated) is being triggered when grid item is being vertically compacted. 

There is also an event on the item (moved) that is not being triggered in this case. So there is really no other way to determine that the grid has changed unless I am missing something.

**Comment by gmsa** [comment]
@pajcho can you remove the built files from the PR?

**Comment by pajcho** [comment]
> @pajcho can you remove the built files from the PR?

Done 👍 I removed `package-lock.json` as well

**Comment by gmsa** [comment]
@pajcho I ended up adding the layout-updated event after every compact. See if version 2.3.8 works for you that way.

**Pull request closed without merging**
