### PR TITLE
Fix eventBus to support multiples instances of Grid Layout

### PR DESCRIPTION
**Pull request by LaercioSantana**
Hi, 

I fixed eventBus to support multiples instances of Grid Layouts.

### CODE REVIEW

**Comment by gmsa** [comment]
Can you supply a working example for this?

**Comment by LaercioSantana** [comment]
here:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Vue Grid Layout Example 3 - Multiple instances</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="app.css">
</head>
<body>
    <div id="app1" style="width: 100%;">
        <h3> app1 </h3>
        <div id="content">
            <grid-layout :layout="layout"
                         :col-num="12"
                         :row-height="30"
                         :is-draggable="true"
                         :is-resizable="true"
                         :vertical-compact="true"
                         :use-css-transforms="true"
            >
                <grid-item v-for="item in layout"
                           :x="item.x"
                           :y="item.y"
                           :w="item.w"
                           :h="item.h"
                           :i="item.i"
                        >
                    <span class="text">{{item.i}}</span>
                </grid-item>
            </grid-layout>
        </div>
    </div>
    <hr/>
    <div id="app2" style="width: 100%;">
        <h3> app2 </h3>
        <div id="content">
            <grid-layout :layout="layout"
                         :col-num="12"
                         :row-height="30"
                         :is-draggable="true"
                         :is-resizable="true"
                         :vertical-compact="true"
                         :use-css-transforms="true"
            >
                <grid-item v-for="item in layout"
                           :x="item.x"
                           :y="item.y"
                           :w="item.w"
                           :h="item.h"
                           :i="item.i"
                        >
                    <span class="text">{{item.i}}</span>
                </grid-item>
            </grid-layout>
        </div>
    </div>

    <script src="vue.min.js"></script>
    <script src="../dist/vue-grid-layout.js"></script>
    <script type="text/javascript">
        Vue.config.debug = true;
        Vue.config.devtools = true;

        var GridLayout = VueGridLayout.GridLayout;
        var GridItem = VueGridLayout.GridItem;


        new Vue({
            el: '#app1',
            components: {
                GridLayout,
                GridItem,
            },
            data: {
                layout: [
                    {"x":0,"y":0,"w":2,"h":2,"i":"0"},
                    {"x":2,"y":0,"w":2,"h":4,"i":"1"},
                ],
                index: 0
            },
        });

        new Vue({
            el: '#app2',
            components: {
                GridLayout,
                GridItem,
            },
            data: {
                layout: [
                    {"x":0,"y":0,"w":2,"h":2,"i":"0"},
                    {"x":2,"y":0,"w":2,"h":4,"i":"1"},
                    {"x":4,"y":0,"w":2,"h":2,"i":"2"},
                ],
                index: 0
            },
        });



    </script>
</body>
</html>
```

put this code inside 'vue-grid-layout/examples'. When drag a item 0 from app1, a item 0 from app2 will too move. This happen because eventeBus send drag event to all apps. Now, try same example in my branch, and this works. 

Obs: the correct way to communicate components is explaned [here](https://vuejs.org/v2/guide/components.html#Composing-Components), but I opted to do a quick fix and proceeded using eventBus.

**Comment by gmsa** [comment]
About the correct way to component communication, can you be more specific? 
Are you talking about using v-on on the parent component template? Because according to [this](https://vuejs.org/v2/guide/components.html#Using-v-on-with-Custom-Events), you cannot use $on to listen to events emitted by children.

**Comment by LaercioSantana** [comment]
ok, i'll try explain

it's we have:
"the parent need to pass data down to the child, and the child need to inform the parent of something that happened in the child"

You has implemented this behavior through the eventBus, but it is a bad way to implements this behavior, because eventBus is used by all components of type GridLayout and GridItem.

Vue documentations advise us:
"In Vue.js, the parent-child component relationship can be summarized as props down, events up. The parent passes data down to the child via props, and the child sends messages to the parent via events."

So, GridLayout should send data to GridItem through the props, not through eventBus. Still GridItem should send data to GridLayout through the  local events, as ```v-on:foo```.

**Comment by gmsa** [comment]
Yes, I had already read using v-on on the template, but that won't work here, since the grid-item components are declared on a slot whenever grid-layout is used by someone. 

It would be necessary for everyone to declare all the v-on events severy time someone uses the grid.

**Comment by LaercioSantana** [comment]
I had forgot slots, sorry, you are correct.

**Comment by gmsa** [comment]
#32 fixes this using [provide/inject](https://vuejs.org/v2/api/#provide-inject). Thanks for your help.

**Pull request closed without merging**
