### PR TITLE
Feature, transformScale

### PR DESCRIPTION
**Pull request by adt-hgkim**

### CODE REVIEW

**Comment by adt-hgkim** [comment]
It's my first PR. Help me how to build please.

**Comment by adt-hgkim** [comment]
I think now It works

**Comment by gmsa** [comment]
I'll have a look into it later

**Comment by adt-hgkim** [comment]
I found bug on minW and minH. It cannot be fixed correctly when layout is scaled.

**Comment by Flourad** [comment]
> I'll have a look into it later
How to use this feature, I need the transformScale ?

**Comment by adt-hgkim** [comment]
> > I'll have a look into it later
> > How to use this feature, I need the transformScale ?

Maybe, try this.
`npm install github:adt-hgkim/vue-grid-layout#transformScale`

**Comment by Flourad** [comment]
> npm install github:adt-hgkim/vue-grid-layout#transformScale

why the  transformScale branch are not merged into the master?

**Comment by Flourad** [comment]
> I'll have a look into it later

Could you merge this feature into the master branch?

**Comment by adt-hgkim** [comment]
> > I'll have a look into it later
> 
> Could you merge this feature into the master branch?

I just have merged into master on adt-hgkim/vue-grid-layout

**Comment by wkl007** [comment]
we need this!!!

**Comment by gmsa** [comment]
@wkl007 We have a regular job and do this on our free time. Do you want to sponsor this merge by paying for our time?

**Comment by wkl007** [comment]
@gmsa Sorry,i don't want to do it

**Comment by charlesgourdin** [comment]
Hi, does this PR will be merged?

**Pull request merged**
